[package]
name = "nncombinator"
version = "0.9.0"
authors = ["jinpu <nanasi18@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
description = "A library of neural networks that can be written type-safely"
documentation = "https://docs.rs/nncombinator/"
homepage = "https://crates.io/crates/nncombinator"
repository = "https://github.com/j6k1/nncombinator"
readme = "README.md"

keywords = ["neural-network","machine-learning","numeric-calculation"]
categories = ["mathematics","science"]
license = "MIT"

build = "build.rs"
[features]
default = ["cuda"]
cuda = ["cuda-runtime-sys","rcudnn","rcudnn-sys","rcublas","rcublas-sys"]
[dependencies]
num-traits = "0.2.14"
rayon = "1.5.1"
libc = "0.2"
try-from-primitive = "0.1.0"
cuda-runtime-sys = { version = "0.3.0-alpha.1", optional = true }
rcudnn = { version =  "1.8.0", optional = true }
rcudnn-sys = { version = "0.5.0", optional = true }
rcublas = { version = "0.6.0", optional = true }
rcublas-sys = { version = "0.5.0", optional = true }
[dev-dependencies]
rand = "0.8.5"
rand_xorshift = "0.3.0"
statrs = "0.15.0"
rand_distr = "0.4.3"
csv = "1.1.6"
lazy_static = "1.4.0"
image = "0.24.4"
mnist = "0.5.0"
[build-dependencies]
cc = "1.0.95"
[profile.test]
opt-level = 3
codegen-units = 1
lto = true